
package pe.gob.mtc.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Tue Mar 15 11:22:37 COT 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "searchRepresentante", namespace = "http://mtc.gob.pe/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchRepresentante", namespace = "http://mtc.gob.pe/", propOrder = {"nombres", "apellidos", "tipo", "numDoc"})

public class SearchRepresentante {

    @XmlElement(name = "nombres")
    private java.lang.String nombres;
    @XmlElement(name = "apellidos")
    private java.lang.String apellidos;
    @XmlElement(name = "tipo")
    private java.lang.String tipo;
    @XmlElement(name = "numDoc")
    private java.lang.String numDoc;

    public java.lang.String getNombres() {
        return this.nombres;
    }

    public void setNombres(java.lang.String newNombres)  {
        this.nombres = newNombres;
    }

    public java.lang.String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(java.lang.String newApellidos)  {
        this.apellidos = newApellidos;
    }

    public java.lang.String getTipo() {
        return this.tipo;
    }

    public void setTipo(java.lang.String newTipo)  {
        this.tipo = newTipo;
    }

    public java.lang.String getNumDoc() {
        return this.numDoc;
    }

    public void setNumDoc(java.lang.String newNumDoc)  {
        this.numDoc = newNumDoc;
    }

}

