
package pe.gob.mtc.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Tue Mar 15 11:22:37 COT 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "serachConsultora", namespace = "http://mtc.gob.pe/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serachConsultora", namespace = "http://mtc.gob.pe/", propOrder = {"codigo", "RUC", "razonSocial", "nacionalidad"})

public class SerachConsultora {

    @XmlElement(name = "codigo")
    private java.lang.String codigo;
    @XmlElement(name = "RUC")
    private java.lang.String RUC;
    @XmlElement(name = "razonSocial")
    private java.lang.String razonSocial;
    @XmlElement(name = "nacionalidad")
    private java.lang.String nacionalidad;

    public java.lang.String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(java.lang.String newCodigo)  {
        this.codigo = newCodigo;
    }

    public java.lang.String getRUC() {
        return this.RUC;
    }

    public void setRUC(java.lang.String newRUC)  {
        this.RUC = newRUC;
    }

    public java.lang.String getRazonSocial() {
        return this.razonSocial;
    }

    public void setRazonSocial(java.lang.String newRazonSocial)  {
        this.razonSocial = newRazonSocial;
    }

    public java.lang.String getNacionalidad() {
        return this.nacionalidad;
    }

    public void setNacionalidad(java.lang.String newNacionalidad)  {
        this.nacionalidad = newNacionalidad;
    }

}

